/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication4;
import java.util.HashSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.LinkedList;
import java.io.*;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.net.DatagramPacket;
import java.nio.charset.StandardCharsets;
/**
 *
 * @author alksejvidaev
 */
public class lb1UI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(lb1UI.class.getName());
    private static LinkedList<RecIntegral> records;
    private java.net.DatagramSocket registerSocket;
    private java.net.DatagramSocket taskSocket;
    private java.util.List<UDPClientInfo> clients = new java.util.ArrayList<>();
    private boolean serverRunning = false;
    /**
     * Creates new form lb1UI
     */
    private static final int REGISTER_PORT = 6000;
    private static final int TASK_PORT = 6001;
    public lb1UI() {
    initComponents();
    records = new LinkedList<>();
    startServer(REGISTER_PORT);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButtonAdd = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jButtonCalculate = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButtonFill = new javax.swing.JButton();
        jButtonClear = new javax.swing.JButton();
        jButtonReadD = new javax.swing.JButton();
        jButtonReadText = new javax.swing.JButton();
        jButtonWriteD = new javax.swing.JButton();
        jButtonWriteT = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 255));

        jPanel2.setBackground(new java.awt.Color(255, 153, 255));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel1.setText("Вычисление интеграла");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel2.setText("sqrt(x)");

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel3.setText("вп");

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel4.setText("нп");

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel5.setText("шагг");

        jTextField2.addActionListener(this::jTextField2ActionPerformed);

        jButtonAdd.setBackground(new java.awt.Color(255, 153, 255));
        jButtonAdd.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jButtonAdd.setText("добавить");
        jButtonAdd.addActionListener(this::jButtonAddActionPerformed);

        jButtonDelete.setBackground(new java.awt.Color(255, 153, 255));
        jButtonDelete.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jButtonDelete.setText("Удалить");
        jButtonDelete.addActionListener(this::jButtonDeleteActionPerformed);

        jButtonCalculate.setBackground(new java.awt.Color(255, 153, 255));
        jButtonCalculate.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jButtonCalculate.setText("Вычислить");
        jButtonCalculate.setToolTipText("");
        jButtonCalculate.addActionListener(this::jButtonCalculateActionPerformed);

        jTable2.setBackground(new java.awt.Color(255, 204, 255));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "нп", "вп", "шаг", "результат"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jButtonFill.setBackground(new java.awt.Color(255, 153, 255));
        jButtonFill.setText("заполнить");
        jButtonFill.addActionListener(this::jButtonFillActionPerformed);

        jButtonClear.setBackground(new java.awt.Color(255, 153, 255));
        jButtonClear.setText("очистить");
        jButtonClear.addActionListener(this::jButtonClearActionPerformed);

        jButtonReadD.setBackground(new java.awt.Color(255, 153, 255));
        jButtonReadD.setText("Загрузить из файла двоичный");
        jButtonReadD.setActionCommand("fReadD");
        jButtonReadD.addActionListener(this::jButtonReadDActionPerformed);

        jButtonReadText.setBackground(new java.awt.Color(255, 153, 255));
        jButtonReadText.setText("Загрузить из текстового файла");
        jButtonReadText.setActionCommand("fReadT");
        jButtonReadText.addActionListener(this::jjButtonReadTextActionPerformed);

        jButtonWriteD.setBackground(new java.awt.Color(255, 153, 255));
        jButtonWriteD.setText("Загрузить в файл двоич");
        jButtonWriteD.addActionListener(this::jButtonWriteDActionPerformed);

        jButtonWriteT.setBackground(new java.awt.Color(255, 153, 255));
        jButtonWriteT.setText("Загрузить в текстовый файл ");
        jButtonWriteT.addActionListener(this::jButtonWriteTActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane2)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                                        .addComponent(jTextField3))
                                    .addGap(103, 103, 103)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jButtonCalculate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButtonDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(103, 103, 103)
                                    .addComponent(jButtonAdd, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButtonFill)
                                .addComponent(jButtonClear)))
                        .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonReadD)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonReadText))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonWriteD)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonWriteT)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jButtonAdd)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDelete)
                    .addComponent(jButtonClear))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCalculate)
                    .addComponent(jButtonFill))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonReadD)
                    .addComponent(jButtonReadText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonWriteD)
                    .addComponent(jButtonWriteT))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 468, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void startServer(int port) {
    System.out.println("Запуск UDP-сервера регистрации");

    if (serverRunning) {
        System.out.println("Сервер уже запущен");
        return;
    }

    Thread serverThread = new Thread(() -> {
        try {
            registerSocket = new java.net.DatagramSocket(port);
            taskSocket = new java.net.DatagramSocket(TASK_PORT);
            serverRunning = true;

            System.out.println("REGISTER socket запущен на порту " + port);
            System.out.println("TASK/RESULT socket запущен на порту " + TASK_PORT);

            while (serverRunning) {
                byte[] buffer = new byte[1024];
                DatagramPacket packet = new DatagramPacket(buffer, buffer.length);
                registerSocket.receive(packet);

                String message = new String(
                        packet.getData(),
                        0,
                        packet.getLength(),
                        java.nio.charset.StandardCharsets.UTF_8
                );

                System.out.println("REGISTER socket получил: " + message);

                if ("REGISTER".equals(message)) {
                    UDPClientInfo client = new UDPClientInfo(packet.getAddress(), packet.getPort());

                    synchronized (clients) {
                        if (!clients.contains(client)) {
                            clients.add(client);
                            System.out.println("Клиент зарегистрирован: " + client);
                        } else {
                            System.out.println("Клиент уже зарегистрирован: " + client);
                        }
                    }
                }
            }
        } catch (Exception e) {
            if (serverRunning) {
                System.out.println("Ошибка в startServer:");
                e.printStackTrace();
            }
        }
    });

    serverThread.start();
    System.out.println("Поток регистрации запущен");
}
private double calculateDistributed(double lower, double upper, double step) throws Exception {    java.util.List<UDPClientInfo> activeClients;

    synchronized (clients) {
        activeClients = new java.util.ArrayList<>(clients);
    }

    System.out.println("Клиентов для вычисления: " + activeClients.size());

    if (activeClients.isEmpty()) {
        throw new Exception("Нет подключенных клиентов.");
    }

    int clientCount = activeClients.size();
    double intervalLength = upper - lower;
    double partLength = intervalLength / clientCount;

    double start = lower;

    // Отправка TASK всем клиентам через отдельный сокет
    for (int i = 0; i < clientCount; i++) {
        double end = (i == clientCount - 1) ? upper : start + partLength;

        String taskMessage = "TASK;" + start + ";" + end + ";" + step;
        byte[] taskData = taskMessage.getBytes(StandardCharsets.UTF_8);

        UDPClientInfo client = activeClients.get(i);

        DatagramPacket packet = new DatagramPacket(
                taskData,
                taskData.length,
                client.getAddress(),
                client.getPort()
        );

        System.out.println("Отправка TASK клиенту " + client + ": " + taskMessage);
        taskSocket.send(packet);

        start = end;
    }

    // Ждём RESULT только на taskSocket
    taskSocket.setSoTimeout(10000);

    double total = 0.0;
    int receivedResults = 0;

    while (receivedResults < clientCount) {
        try {
            byte[] buffer = new byte[1024];
            DatagramPacket packet = new DatagramPacket(buffer, buffer.length);

            System.out.println("Ожидание RESULT... " + (receivedResults + 1) + "/" + clientCount);
            taskSocket.receive(packet);

            String message = new String(
                    packet.getData(),
                    0,
                    packet.getLength(),
                    StandardCharsets.UTF_8
            );

            System.out.println("TASK socket получил: " + message +
                    " от " + packet.getAddress().getHostAddress() + ":" + packet.getPort());

            if (message.startsWith("RESULT;")) {
                String[] parts = message.split(";");
                double partial = Double.parseDouble(parts[1]);
                total += partial;
                receivedResults++;

                System.out.println("Частичный результат принят: " + partial);
            } else {
                System.out.println("Игнорируется сообщение: " + message);
            }

        } catch (java.net.SocketTimeoutException e) {
            throw new Exception("Истекло время ожидания ответов от клиентов.");
        }
    }

    taskSocket.setSoTimeout(0);

    System.out.println("Итоговый результат: " + total);
    return total;
}
    
    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        // TODO add your handling code here:
        try {
        String lowerStr = jTextField1.getText().trim();
        String upperStr = jTextField2.getText().trim();
        String stepStr = jTextField3.getText().trim();

        double lower = Double.parseDouble(lowerStr);
        double upper = Double.parseDouble(upperStr);
        double step = Double.parseDouble(stepStr);

        // Создание объекта с проверкой диапазона
        if(lower > upper){
            double temp = lower;
            lower = upper;
            upper = temp;
        }
        RecIntegral rec = new RecIntegral(lower, upper, step);
        records.add(rec);

        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        model.addRow(new Object[]{lower, upper, step, ""});

        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");

    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this,
            "Пожалуйста, введите корректные числа (разделитель дробной части — точка).",
            "Ошибка ввода", JOptionPane.ERROR_MESSAGE);
    } catch (InvalidRangeException ex) {
        JOptionPane.showMessageDialog(this,
            ex.getMessage(),
            "Ошибка диапазона", JOptionPane.WARNING_MESSAGE);
    }
        
    }//GEN-LAST:event_jButtonAddActionPerformed
    
    private void refreshTable() {
    DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
    model.setRowCount(0);

    for (RecIntegral rec : records) {
        String resultStr = (rec.getResult() == null) ? "" : String.format("%.4f", rec.getResult());
        model.addRow(new Object[]{
            rec.getLower(),
            rec.getUpper(),
            rec.getStep(),
            resultStr
        });
    }
}
    private void saveToTextFile(File file) {
    try (PrintWriter writer = new PrintWriter(new FileWriter(file))) {
        for (RecIntegral rec : records) {
            String resultStr = (rec.getResult() == null) ? "" : rec.getResult().toString();
            writer.println(rec.getLower() + ";" +
                           rec.getUpper() + ";" +
                           rec.getStep() + ";" +
                           resultStr);
        }

        JOptionPane.showMessageDialog(this,
                "Данные успешно сохранены в текстовый файл.",
                "Успех",
                JOptionPane.INFORMATION_MESSAGE);

    } catch (IOException e) {
        JOptionPane.showMessageDialog(this,
                "Ошибка сохранения текстового файла: " + e.getMessage(),
                "Ошибка",
                JOptionPane.ERROR_MESSAGE);
    }
}
    private void loadFromTextFile(File file) {
    LinkedList<RecIntegral> tempList = new LinkedList<>();

    try (BufferedReader reader = new BufferedReader(new FileReader(file))) {
        String line;

        while ((line = reader.readLine()) != null) {
            if (line.trim().isEmpty()) continue;

            String[] parts = line.split(";");
            if (parts.length < 4) {
                throw new IOException("Некорректный формат строки: " + line);
            }

            double lower = Double.parseDouble(parts[0]);
            double upper = Double.parseDouble(parts[1]);
            double step = Double.parseDouble(parts[2]);

            RecIntegral rec = new RecIntegral(lower, upper, step);

            if (!parts[3].isEmpty()) {
                rec.setResult(Double.parseDouble(parts[3]));
            }

            tempList.add(rec);
        }

        records.clear();
        records.addAll(tempList);
        refreshTable();

        JOptionPane.showMessageDialog(this,
                "Данные успешно загружены из текстового файла.",
                "Успех",
                JOptionPane.INFORMATION_MESSAGE);

    } catch (IOException | NumberFormatException | InvalidRangeException e) {
        JOptionPane.showMessageDialog(this,
                "Ошибка загрузки текстового файла: " + e.getMessage(),
                "Ошибка",
                JOptionPane.ERROR_MESSAGE);
    }
}
    private void saveToBinaryFile(File file) {
    try (ObjectOutputStream out = new ObjectOutputStream(
            new BufferedOutputStream(new FileOutputStream(file)))) {

        out.writeObject(records);

        JOptionPane.showMessageDialog(this,
                "Данные успешно сохранены в двоичный файл.",
                "Успех",
                JOptionPane.INFORMATION_MESSAGE);

    } catch (IOException e) {
        JOptionPane.showMessageDialog(this,
                "Ошибка сохранения двоичного файла: " + e.getMessage(),
                "Ошибка",
                JOptionPane.ERROR_MESSAGE);
    }
}
    @SuppressWarnings("unchecked")
private void loadFromBinaryFile(File file) {
    try (ObjectInputStream in = new ObjectInputStream(
            new BufferedInputStream(new FileInputStream(file)))) {

        Object obj = in.readObject();

        if (obj instanceof LinkedList<?>) {
            records = (LinkedList<RecIntegral>) obj;
            refreshTable();

            JOptionPane.showMessageDialog(this,
                    "Данные успешно загружены из двоичного файла.",
                    "Успех",
                    JOptionPane.INFORMATION_MESSAGE);
        } else {
            throw new IOException("Файл не содержит нужных данных.");
        }

    } catch (IOException | ClassNotFoundException e) {
        JOptionPane.showMessageDialog(this,
                "Ошибка загрузки двоичного файла: " + e.getMessage(),
                "Ошибка",
                JOptionPane.ERROR_MESSAGE);
    }
}
    private File chooseFileToOpen(String extension, String description) {
    JFileChooser chooser = new JFileChooser();
    chooser.setFileFilter(new FileNameExtensionFilter(description, extension));

    int result = chooser.showOpenDialog(this);
    if (result == JFileChooser.APPROVE_OPTION) {
        return chooser.getSelectedFile();
    }
    return null;
}
    private File chooseFileToSave(String extension, String description) {
    JFileChooser chooser = new JFileChooser();
    chooser.setFileFilter(new FileNameExtensionFilter(description, extension));

    int result = chooser.showSaveDialog(this);
    if (result == JFileChooser.APPROVE_OPTION) {
        File file = chooser.getSelectedFile();

        if (!file.getName().toLowerCase().endsWith("." + extension)) {
            file = new File(file.getAbsolutePath() + "." + extension);
        }

        return file;
    }
    return null;
}
    
    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        int selected = jTable2.getSelectedRow();
    if (selected == -1) {
        JOptionPane.showMessageDialog(this,
            "Выберите строку для удаления.",
            "Предупреждение", JOptionPane.WARNING_MESSAGE);
        return;
    }

    // Удаляем из коллекции
    records.remove(selected);

    // Удаляем из таблицы
    DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
    model.removeRow(selected);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jButtonCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalculateActionPerformed
   int selected = jTable2.getSelectedRow();
    if (selected == -1) {
        JOptionPane.showMessageDialog(this,
            "Выберите строку для вычисления.",
            "Предупреждение", JOptionPane.WARNING_MESSAGE);
        return;
    }

    DefaultTableModel model = (DefaultTableModel) jTable2.getModel();

    try {
        double lower = Double.parseDouble(model.getValueAt(selected, 0).toString());
        double upper = Double.parseDouble(model.getValueAt(selected, 1).toString());
        double step = Double.parseDouble(model.getValueAt(selected, 2).toString());

        RecIntegral rec = records.get(selected);
        rec.setLower(lower);
        rec.setUpper(upper);
        rec.setStep(step);

        jButtonCalculate.setEnabled(false);

        new Thread(() -> {
            try {
                double result = calculateDistributed(lower, upper, step);
                rec.setResult(result);

                javax.swing.SwingUtilities.invokeLater(() -> {
                    model.setValueAt(String.format("%.4f", result), selected, 3);
                    jButtonCalculate.setEnabled(true);

                    JOptionPane.showMessageDialog(this,
                        "UDP-вычисление завершено.",
                        "Успех",
                        JOptionPane.INFORMATION_MESSAGE);
                });

            } catch (Exception e) {
                javax.swing.SwingUtilities.invokeLater(() -> {
                    jButtonCalculate.setEnabled(true);
                    JOptionPane.showMessageDialog(this,
                        "Ошибка вычисления: " + e.getMessage(),
                        "Ошибка",
                        JOptionPane.ERROR_MESSAGE);
                });
            }
        }).start();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this,
            "Ошибка в данных строки: " + e.getMessage(),
            "Ошибка", JOptionPane.ERROR_MESSAGE);
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCalculateActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButtonFillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFillActionPerformed
        refreshTable();
    }//GEN-LAST:event_jButtonFillActionPerformed

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed

    // Очищаем таблицу
    DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
    model.setRowCount(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonClearActionPerformed

    private void jButtonWriteTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonWriteTActionPerformed
        // TODO add your handling code here:
         File file = chooseFileToSave("txt", "Текстовые файлы (*.txt)");
        if (file != null) {
            saveToTextFile(file);
        }
    }//GEN-LAST:event_jButtonWriteTActionPerformed

    private void jButtonReadDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReadDActionPerformed
        // TODO add your handling code here:
        File file = chooseFileToOpen("dat", "Двоичные файлы (*.dat)");
        if (file != null) {
            loadFromBinaryFile(file);
        }
    }//GEN-LAST:event_jButtonReadDActionPerformed

    private void jjButtonReadTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jjButtonReadTextActionPerformed
        // TODO add your handling code here:
        File file = chooseFileToOpen("txt", "Текстовые файлы (*.txt)");
        if (file != null) {
            loadFromTextFile(file);
        }
    }//GEN-LAST:event_jjButtonReadTextActionPerformed

    private void jButtonWriteDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonWriteDActionPerformed
        // TODO add your handling code here:
        File file = chooseFileToSave("dat", "Двоичные файлы (*.dat)");
        if (file != null) {
            saveToBinaryFile(file);
        }
    }//GEN-LAST:event_jButtonWriteDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new lb1UI().setVisible(true));
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonCalculate;
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonFill;
    private javax.swing.JButton jButtonReadD;
    private javax.swing.JButton jButtonReadText;
    private javax.swing.JButton jButtonWriteD;
    private javax.swing.JButton jButtonWriteT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
